### PR TITLE
fix: force `wgpu` to use dedicated/discrete graphics-card, to avoid Vulkan issues

### LINKED ISSUE #848: bug: Wayland crash when runnning on Vulkan, switching wgpu backend to GL fixes the issue
### Describe the bug

Running using either of:

`./uad-ng-noselfupdate-linux`
`WGPU_BACKEND=vulkan ./uad-ng-noselfupdate-linux`

results in a crash with error (see log).

Runs normally using: `WGPU_BACKEND=gl ./uad-ng-noselfupdate-linux`

### Expected behavior

No crash.

### You have a solution?

Instead of using vulkan backend, use gl.

https://github.com/gfx-rs/wgpu?tab=readme-ov-file#environment-variables

Run with: `WGPU_BACKEND=gl ./uad-ng-noselfupdate-linux`.

### Operating System

Linux

### Distro version

Fedora 41

### Window System + Manager

interface: 'wl_compositor', version:  6, name:  1 | KWin version: 6.2.5

### Desktop Environment

KDE Plasma 6.2.5

### ADB version

_No response_

### Provide logs

<details><summary>Log (copy paste from terminal)</summary>

```
[destroyed object]: error 7: importing the supplied dmabufs failed
Protocol error 7 on object @0: 
Protocol error 7 on object @0: 
2025-02-12 16:54:25 ERROR [/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.19.4/src/vulkan/adapter.rs:1824] get_physical_device_surface_present_modes: ERROR_SURFACE_LOST_KHR
Protocol error 7 on object @0: 
Protocol error 7 on object @0: 2025-02-12 16:54:25 ERROR [/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.19.4/src/vulkan/adapter.rs:1839] get_physical_device_surface_formats: ERROR_SURFACE_LOST_KHR

thread 'Protocol error main7' panicked at  on object /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.19.4/src/device/global.rs@:01859: :
21:
Protocol error internal error: entered unreachable code: Fallback system failed to choose present mode. This is a bug. Mode: AutoVsync, Options: []7
 on object note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
@0: 
Protocol error 7 on object @0: 
Protocol error 7 on object @0: 
Protocol error 7 on object @0: 
Protocol error 7 on object @0: 
Protocol error 7 on object @0: 
Protocol error 7 on object @0: 
Protocol error 7 on object @0: 
Protocol error 7 on object @0: 
Protocol error 7 on object @0: 
Protocol error 7 on object @0:
```
</details>

<details><summary>Log (UAD_20250212.log)</summary>

```
2025-02-12 16:54:25 ERROR [/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.19.4/src/vulkan/adapter.rs:1824] get_physical_device_surface_present_modes: ERROR_SURFACE_LOST_KHR
2025-02-12 16:54:25 ERROR [/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.19.4/src/vulkan/adapter.rs:1839] get_physical_device_surface_formats: ERROR_SURFACE_LOST_KHR

```
</details>

### Acknowledgements

- [x] This issue is not a duplicate of an existing bug report.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

### PR DESCRIPTION
**Pull request by user583953**
I've spent like an hour looking through Iced, and apparently there is no option to pass config to wgpu, it always picks settings from env:

https://docs.rs/iced_renderer/0.12.1/src/iced_renderer/compositor.rs.html#252
https://docs.rs/iced_wgpu/0.12.1/src/iced_wgpu/settings.rs.html#47

Also, for some reason, on my PC setting via WGPU_BACKEND=gl (either in terminal or using set_env) only fixes the issue when compiling with `--release`.

fixes #848

### CODE REVIEW

**Review by adhirajsinghchauhan — CHANGES_REQUESTED** [review]
I'm hesitant to merge this, to avoid this issue popping up again. Even though GL is a much older standard than Vulkan, forcing GL-only for everyone may again lead to similar issues in the future. Also, as far as I understand it, Vulkan, if used properly, offers lower power usage for the same performance (less overhead). It shouldn't make that much of a difference for this project, but it goes in line with our debloater ethos.

If it's only wayland that crashes, wouldn't the better solution be to use GL _only_ for wayland? Users can set the env in their home configs for now.

Side-note: do we know that it crashes for all wayland users, or only the reporter?

**Comment by user583953** [comment]
> wouldn't the better solution be to use GL only for wayland?

I can add check for `XDG_SESSION_TYPE=wayland`, and if true, use GL.

> do we know that it crashes for all wayland users, across all distros, or only for the reporter?

I've looked for similar issues based on the crash log:

#459 fail with either Wayland/Xorg + Nvidia.

[This](https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/383#issuecomment-2022836325) comment from #383 mentions AMD + Wayland though it's old,

and the #383 itself mentions problem with Nvidia + Xorg and lack of it with AMD + Wayland.

https://github.com/gfx-rs/wgpu/issues/6159 Nvidia + Wayland and a comment that the problem also occurs on AMD + Wayland.

https://github.com/gfx-rs/wgpu/issues/6320 Nvidia + Wayland.

One of those issues mentions improper usage of surface, so I tried to run an Iced example from the latest branch to see if it was fixed, it failed, but it had a nice crash log:

```
2025-02-15T11:05:54.734378Z  INFO iced_wgpu::window::compositor: Available adapters: [
    AdapterInfo {
        name: "NVIDIA GeForce GTX 1050",
        vendor: 4318,
        device: 7297,
        device_type: DiscreteGpu,
        driver: "NVIDIA",
        driver_info: "565.77",
        backend: Vulkan,
    },
    AdapterInfo {
        name: "AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO)",
        vendor: 4098,
        device: 5710,
        device_type: IntegratedGpu,
        driver: "radv",
        driver_info: "Mesa 24.3.4",
        backend: Vulkan,
    },
    AdapterInfo {
        name: "llvmpipe (LLVM 19.1.7, 256 bits)",
        vendor: 65541,
        device: 0,
        device_type: Cpu,
        driver: "llvmpipe",
        driver_info: "Mesa 24.3.4 (LLVM 19.1.7)",
        backend: Vulkan,
    },
    AdapterInfo {
        name: "NVIDIA GeForce GTX 1050/PCIe/SSE2",
        vendor: 4318,
        device: 0,
        device_type: Other,
        driver: "",
        driver_info: "",
        backend: Gl,
    },
]    
2025-02-15T11:05:54.739952Z  INFO wgpu_core::instance: Adapter Vulkan AdapterInfo { name: "AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO)", vendor: 4098, device: 5710, device_type: IntegratedGpu, driver: "radv", driver_info: "Mesa 24.3.4", backend: Vulkan }    
2025-02-15T11:05:54.739990Z  INFO iced_wgpu::window::compositor: Selected: AdapterInfo {
    name: "AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO)",
    vendor: 4098,
    device: 5710,
    device_type: IntegratedGpu,
    driver: "radv",
    driver_info: "Mesa 24.3.4",
    backend: Vulkan,
}

[...edited out...]

[destroyed object]: error 7: importing the supplied dmabufs failed
Protocol error 7 on object @0: 
2025-02-15T11:05:54.847644Z ERROR wgpu_hal::vulkan::adapter: get_physical_device_surface_present_modes: ERROR_SURFACE_LOST_KHR    
2025-02-15T11:05:54.847665Z ERROR wgpu_hal::vulkan::adapter: get_physical_device_surface_formats: ERROR_SURFACE_LOST_KHR    
thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.19.4/src/device/global.rs:1859:21:
internal error: entered unreachable code: Fallback system failed to choose present mode. This is a bug. Mode: AutoVsync, Options: []
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I am on PC and monitor is connected to Nvidia dGPU, not on a laptop, but it selected AMD iGPU instead. There's a similar issue: https://github.com/gfx-rs/wgpu/issues/3747 mentions Nvidia + Intel hybrid laptop + Xorg

I'll create an issue on Iced issue tracker later.

**Comment by Rudxain** [comment]
> wouldn't the better solution be to use GL _only_ for wayland?

I was thinking of a simple mechanism for UAD to detect when it crashes, so that the next startup forces GL-use to try to prevent a crash. This is **very** hacky, so false positives/negatives would be detected. For example, depending on implementation details, an unclean computer-shutdown would make the next UADNG startup assume a crash happened.

> Users can set the env in their home configs for now

I agree, we should add this to the FAQ. I'll do it in a minute.

> Side-note: do we know that it crashes for all wayland users, across all distros, or only for the reporter?

I remember Windows users having issues with Vulkan, too

**Comment by user583953** [comment]
I did some more investigation (see my comment at https://github.com/gfx-rs/wgpu/issues/6159), and it looks like the problem is that it selects Amd iGPU for some reason. If I force wgpu to use dGPU via `WGPU_POWER_PREF=high`, it selects Nvidia dGPU on Vulkan and runs fine.

Running on dGPU will not force either GL or Vulkan on users, but will prevent crashes at the cost of slightly higher power usage on laptops.

**Comment by AnonymousWP** [comment]
Thank you so much for wanting to fix this issue, it's appreciated.

> Also, for some reason, on my PC setting via WGPU_BACKEND=gl (either in terminal or using set_env) only fixes the issue when compiling with --release.

Is that always or still the case or did you find a workaround?

---

> I'm hesitant to merge this, to avoid this issue popping up again. Even though GL is a much older standard than Vulkan, forcing GL-only for everyone may again lead to similar issues in the future. Also, as far as I understand it, Vulkan, if used properly, offers lower power usage for the same performance (less overhead). It shouldn't make that much of a difference for this project, but it goes in line with our debloater ethos.

That's correct, and I agree.

> Side-note: do we know that it crashes for all wayland users, across all distros, or only for the reporter?

It seems it only affects users using X11:

- https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/523
- https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/459
- https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/383

---

> I can add check for XDG_SESSION_TYPE=wayland, and if true, use GL.

That'd be good

File: src/main.rs [hunk 1]
```diff
@@ -20,6 +20,15 @@ static CACHE_DIR: LazyLock<PathBuf> =
     LazyLock::new(|| setup_uad_dir(&dirs::cache_dir().expect("Can't detect cache dir")));
 
 fn main() -> iced::Result {
+    // Safety: This function is safe to call in a single-threaded program.
+    // The exact requirement is: you must ensure that there are no other threads concurrently writing or
+    // reading(!) the environment through functions or global variables other than the ones in this module.
+    unsafe {
+        // Force WGPU/Iced to use discrete GPU to prevent crashes on PCs with two GPUs.
+        // See #848 and related pull 850.
+        std::env::set_var("WGPU_POWER_PREF", "high");
```
Comment (adhirajsinghchauhan) [inline src/main.rs:29]: Hmm, we'll have to test this before merging. For example, in Windows, you can manually assign programs to use low or high power GPUs (read: iGPU/dGPU), and I wonder if this clashes with that. It probably shouldn't, because we're hardcoding our preference, but who knows?

**Review by adhirajsinghchauhan — APPROVED** [review]

File: src/main.rs (hunk 1 above)
Comment (AnonymousWP) [reply src/main.rs:29]: Because the PR is from a fork, I can't kick off the 'Build artifacts' Action, so we'll 3 options:

1. Merge this first, then build artifacts, but that's a bad practice because then you're merging untested code to master/main.
2. Ask the user to generate build artifacts, but that comes with a risk (nothing personal, just general risk)
3. Create a test branch, then cherry-pick the commit to said branch, then generate build artifacts.

I'd say the third option. 😉

Comment (AnonymousWP) [reply src/main.rs:29]: Done: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/actions/runs/13366107072

Comment (AnonymousWP) [reply src/main.rs:29]: Works fine for me.

Comment (AnonymousWP) [reply src/main.rs:29]: I'll ask users in the linked issues to test this as well.

**Comment by AnonymousWP** [comment]
Let's wait with merging. This user is still experiencing issues: https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/issues/523#issuecomment-2662563349

File: src/main.rs (hunk 1 above)
Comment (adhirajsinghchauhan) [reply src/main.rs:29]: Testing for this specific commit can only be done by people who have both an integrated, an a discrete GPU, and additionally, also those who are on an OS that allows choosing between them on a per-program basis.

The earlier commit (where OpenGL was requested) can be tested by anyone.

Comment (user583953) [reply src/main.rs:29]: Tested on Windows 10 Intel + Nvidia laptop, GPU was chosen using [this](https://pcgearhead.com/switch-intel-graphics-to-nvidia-in-your-laptop/) method (native Windows 10 settings app).

Runs fine with either "Let Windows decide", "Power saving" or "High Performance".

Comment (Rudxain) [reply src/main.rs:29]: > Because the PR is from a fork, I can't kick off the 'Build artifacts' Action

What if we modify the CI itself to be allowed to generate artifacts from PRs? That's [what Termux does](https://github.com/termux/termux-app/actions/workflows/debug_build.yml)

**Comment by user583953** [comment]
I don't think #523 is related. The problem there is that text is not being rendered correctly, while here the problem is hard crash.

Quote from the open https://github.com/iced-rs/iced/issues/2709, which describes the same issue as #523:

> Adding shaping(text::Shaping::Advanced) makes the text render properly. So I'm not sure if it means the default font lookup makes a bad guess, or?

I'll try to make a separate PR tomorrow.

**Comment by AnonymousWP** [comment]
Ah I see, I saw they were both related to `wgpu` or Vulkan. Anyway, I merged this now based on your conclusion. Thanks again. 🙂

File: src/main.rs (hunk 1 above)
Comment (AnonymousWP) [reply src/main.rs:29]: That's possible, but a little heavy and that means the CI needs more time to finish. We also probably don't really need it, but it's easier to test stuff though. I'll create an issue for it.
